---
- name: install httpd with ansible playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd
    yum:
      name: httpd
      state: installed
  - name: start service
    service:
      name: httpd
      state: started